[package]
name = "variables"
version = "0.1.0"
authors = ["Sammy <lixiangmin01@baidu.com>"]
edition = "2018"
default-run = "ok"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
