[package]
name = "04"
version = "0.1.0"
authors = ["Sammy <lixiangmin01@baidu.com>"]
edition = "2018"
description = "Listing 4-4: Transferring ownership of return values"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
